const mongoose = require("mongoose");
const db = require("../models");

// This file empties the Posts collection and inserts the seed below

mongoose.connect(process.env.MONGODB_URI || "mongodb://localhost/reactcms");

const brewerySeed = [
    NodaBrewingCompany = {
        name: "NoDa Brewing Company",
        logo: "",
        location: "Noda, Charlotte",
        website: "http://nodabrewing.com",
        description: "",
        beers =[
            {
                name: "Hop Drop 'N' Roll",
                picture: "",
                price: "",
                description: "",
                type: "IPA",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Jam Session",
                picture: "",
                price: "",
                description: "",
                type: "Pale Ale",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Cavu",
                picture: "",
                price: "",
                description: "",
                type: "Blode Ale",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Coco Loco",
                picture: "",
                price: "",
                description: "",
                type: "Porter",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
        ],
    },
    BirdsongBrewingCompany = {
        name: "Birdsong Brewing Company",
        logo: "",
        location: "Uptown, Charlotte",
        website: "https://birdsongbrewing.com/",
        description: "",
        beers =[
            {
                name: "Higher-Ground",
                picture: "",
                price: "",
                description: "",
                type: "WestCoast IPA",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Jalepeno",
                picture: "",
                price: "",
                description: "",
                type: "Pale Ale",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Lazy Bird",
                picture: "",
                price: "",
                description: "",
                type: "Brown Ale",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Paradise City",
                picture: "",
                price: "",
                description: "",
                type: "IPA",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
        ],
    },
    BlueBlazeBrewing = {
        name: "Blue Blaze Brewing",
        logo: "",
        location: "West End, Charlotte",
        website: "http://www.blueblazebrewing.com/",
        description: "",
        beers =[
            {
                name: "Blue Blaze Altbier",
                picture: "",
                price: "",
                description: "",
                type: "Pilsner",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Yellow Blazer Kolsch",
                picture: "",
                price: "",
                description: "",
                type: "Blonde Ale",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Black Blaze Milk Stout",
                picture: "",
                price: "",
                description: "",
                type: "Stout",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "SoBo Orangerine Hazy IPA",
                picture: "",
                price: "",
                description: "",
                type: "IPA",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
        ],
    },
    BrewersAt4001Yancy = {
        name: "Brewers At 4001 Yancy",
        logo: "",
        location: "LoSO, Charlotte",
        website: "http://brewersat4001yancey.com/",
        description: "",
        beers =[
            {
                name: "Hootie",
                picture: "",
                price: "",
                description: "",
                type: "IPA",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Citrus Jammer",
                picture: "",
                price: "",
                description: "",
                type: "Sour",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Sweet Action",
                picture: "",
                price: "",
                description: "",
                type: "Blonde Ale",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "The Crisp",
                picture: "",
                price: "",
                description: "",
                type: "Pilsner",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
        ],
    },
    Catawba = {
        name: "Catawba",
        logo: "",
        location: "Belmont, Charlotte",
        website: "https://catawbabrewing.com/locations/charlotte",
        description: "",
        beers =[
            {
                name: "El Gato Mariachi",
                picture: "",
                price: "",
                description: "",
                type: "White Ale",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Hopness Haze",
                picture: "",
                price: "",
                description: "",
                type: "IPA",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "White Zombie",
                picture: "",
                price: "",
                description: "",
                type: "White Ale",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Evening Joe",
                picture: "",
                price: "",
                description: "",
                type: "Coffee Blonde Ale",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
        ],
    },
    FreeRangeBrewing = {
        name: "Free Range Brewing",
        logo: "",
        location: "Noda, Charlotte",
        website: "https://www.heistbrewery.com/",
        description: "",
        beers =[
            {
                name: "Common Home",
                picture: "",
                price: "",
                description: "",
                type: "Common Ale",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Therapy Session",
                picture: "",
                price: "",
                description: "",
                type: "Hazy IPA",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "You're Everything I Knead",
                picture: "",
                price: "",
                description: "",
                type: "Sourdough IPA",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Serious Business",
                picture: "",
                price: "",
                description: "",
                type: "Lager",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
        ],
    },
    HeistBrewery = {
        name: "Heist Brewery",
        logo: "",
        location: "",
        website: "",
        description: "",
        beers =[
            {
                name: "Big Pick'n",
                picture: "",
                price: "",
                description: "",
                type: "Sour",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Blurred is the Word",
                picture: "",
                price: "",
                description: "",
                type: "IPA",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Brunch Junkie",
                picture: "",
                price: "",
                description: "",
                type: "Stout",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Druid Pils",
                picture: "",
                price: "",
                description: "",
                type: "Pilsner",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
        ],
    },
    LegionBrewing = {
        name: "Legion Brewing",
        logo: "",
        location: "Plaza Midwood, Charlotte",
        website: "http://legionbrewing.com/",
        description: "",
        beers =[
            {
                name: "Juicy Jay",
                picture: "",
                price: "",
                description: "",
                type: "Hazy IPA",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Penguin Pils",
                picture: "",
                price: "",
                description: "",
                type: "Lager",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Flicker Daze",
                picture: "",
                price: "",
                description: "",
                type: "Wheat Ale",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Carolina Sparkle Party",
                picture: "",
                price: "",
                description: "",
                type: "Berliner Weisse Ale",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
        ],
    },
    LennyBoyBrewing = {
        name: "Lenny Boy Brewing",
        logo: "",
        location: "South End, Charlotte",
        website: "http://www.discoverlennyboy.com/",
        description: "",
        beers =[
            {
                name: "Citraphilia",
                picture: "",
                price: "",
                description: "",
                type: "IPA",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Uno Mas",
                picture: "",
                price: "",
                description: "",
                type: "Lager",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Booty Call",
                picture: "",
                price: "",
                description: "",
                type: "Double IPA",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Tropicalus",
                picture: "",
                price: "",
                description: "",
                type: "White Ale",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
        ],
    },
    OldeMecklenburgBrewery = {
        name: "Olde Mecklenburg Brewery",
        logo: "",
        location: "LoSO, Charlotte",
        website: "http://www.oldemeckbrew.com/",
        description: "",
        beers =[
            {
                name: "Copper",
                picture: "",
                price: "",
                description: "",
                type: "Altbier",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Captain Jack",
                picture: "",
                price: "",
                description: "",
                type: "Pilsner",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Hornets Nest",
                picture: "",
                price: "",
                description: "",
                type: "Hefeweizen",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "704",
                picture: "",
                price: "",
                description: "",
                type: "Hazy Wheat Ale",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
        ],
    },
    ResidentCultureBrewing = {
        name: "Resident Culture Brewing",
        logo: "",
        location: "Plaze Midwood, Charlotte",
        website: "https://residentculturebrewing.com/",
        description: "",
        beers =[
            {
                name: "Double Universe",
                picture: "",
                price: "",
                description: "",
                type: "Hazy Double IPA",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "This Is Just A Test",
                picture: "",
                price: "",
                description: "",
                type: "Hazy IPA",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "PJ Party",
                picture: "",
                price: "",
                description: "",
                type: "Pilsner",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Paegent Worthy",
                picture: "",
                price: "",
                description: "",
                type: "Hazy Double IPA",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
        ],
    },
    SuffolkPunch = {
        name: "Suffolk Punch",
        logo: "",
        location: "South End, Charlotte",
        website: "https://thesuffolkpunch.com/brewery/",
        description: "",
        beers =[
            {
                name: "Bayern Echo",
                picture: "",
                price: "",
                description: "",
                type: "",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Hyde In The Haze",
                picture: "",
                price: "",
                description: "",
                type: "Hazy IPA",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Blue Daisy",
                picture: "",
                price: "",
                description: "",
                type: "",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Pulp Perscription",
                picture: "",
                price: "",
                description: "",
                type: "",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
        ],
    },
    SugarCreekBrewing = {
        name: "Sugar Creek Brewing",
        logo: "",
        location: "LoSO, Charlotte",
        website: "https://sugarcreekbrewing.com/",
        description: "",
        beers =[
            {
                name: "Blood Orange",
                picture: "",
                price: "",
                description: "",
                type: "IPA",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Pale Ale",
                picture: "",
                price: "",
                description: "",
                type: "Pale Ale",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Hazy Creek",
                picture: "",
                price: "",
                description: "",
                type: "IPA",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Raspberry",
                picture: "",
                price: "",
                description: "",
                type: "White Ale",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
        ],
    },
    SycamoreBrewing = {
        name: "Sycamore Brewing",
        logo: "",
        location: "South End, Charlotte",
        website: "https://www.sycamorebrew.com/",
        description: "",
        beers =[
            {
                name: "Mountain Candy",
                picture: "",
                price: "",
                description: "",
                type: "IPA",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Countryside",
                picture: "",
                price: "",
                description: "",
                type: "IPA",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Southern Girl",
                picture: "",
                price: "",
                description: "",
                type: "Blonde Ale",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Rainbow Dust",
                picture: "",
                price: "",
                description: "",
                type: "IPA",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
        ],
    },
    TripleCBrewing = {
        name: "Triple C Brewing",
        logo: "",
        location: "South End, Charlotte",
        website: "http://www.triplecbrewing.com/",
        description: "",
        beers =[
            {
                name: "Golden Boy",
                picture: "",
                price: "",
                description: "",
                type: "Blonde Ale",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Cranes in the Sky",
                picture: "",
                price: "",
                description: "",
                type: "Pale Ale",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Baby Maker",
                picture: "",
                price: "",
                description: "",
                type: "Double IPA",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Bier",
                picture: "",
                price: "",
                description: "",
                type: "German Style Pilsner",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
        ],
    },
    UnknownBrewing = {
        name: "Unknown Brewing",
        logo: "",
        location: "The Gold District, Charlotte",
        website: "http://www.unknownbrewing.com/",
        description: "",
        beers =[
            {
                name: "Feather",
                picture: "",
                price: "",
                description: "",
                type: "Light Berliner",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Over The Edge",
                picture: "",
                price: "",
                description: "",
                type: "IPA",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Pregame",
                picture: "",
                price: "",
                description: "",
                type: "Session Ale",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Tele Porter",
                picture: "",
                price: "",
                description: "",
                type: "Coffee Porter",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
        ],
    },
    WoodenRobotBrewing = {
        name: "Wooden Robot Brewing",
        logo: "",
        location: "South End, Charlotte",
        website: "https://woodenrobotbrewery.com/",
        description: "",
        beers =[
            {
                name: "Botbier",
                picture: "",
                price: "",
                description: "",
                type: "Oak-Aged Saison",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Fluoresent Sunburn",
                picture: "",
                price: "",
                description: "",
                type: "Fruited Ale",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "Overachiever",
                picture: "",
                price: "",
                description: "",
                type: "Juicy IPA",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
            {
                name: "What He's Having",
                picture: "",
                price: "",
                description: "",
                type: "IPA",
                alcoholContent: "",
                quantity: "",
                userReviews = {},
            },
        ],
    },

]

console.log(brewerySeed.brewery1.beers[0]);
